[package]
name = "words5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1.0"
indexmap="1.9"
rayon="1.5"
parking_lot = "0.12"